### ISSUE TITLE
你这个程序绑定的默认端口是什么？

### ISSUE THREAD

**Issue by luckypoem** [acgotaku/IceHoney-BLOG#2]
hi.

root@AR:~/icehoney-blog# python application.py
Traceback (most recent call last):
  File "application.py", line 40, in <module>
    http_server.bind(options.port, options.bind)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 171, in bind
    backlog=backlog)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@AR:~/icehoney-blog#

**Comment by luckypoem** [comment]
看到了，在application.py里面。我把里面的127.0.0.1改为了0.0.0.0，8888改为了9999.
http://surmount.biz.st:9999 ，不够有一点不明白。你这是静态博客程序吗？如果是的话，静态博客网站的根目录在哪里？

root@AR:~/icehoney-blog# ls
application.py	handlers  posts  README.md  static  tpl
root@AR:~/icehoney-blog#

**Comment by acgotaku** [comment]
我这是静态博客啊 运行的时候会把markdown 编译成HTML 网站所有的条目都在  posts里面啊

**Comment by luckypoem** [comment]
我知道是把markdown 编译成HTML 了。我的意思是静态博客网站的根目录在哪里？即包含index.html文件的目录在哪里？我看到其他的静态博客网站程序都会生成一个目录，其中包含了index.html文件

**Comment by acgotaku** [comment]
@luckypoem 根本不存在好么 == 全部 py 进行了重定向

**Comment by luckypoem** [comment]
如果绑定域名，怎么绑呢？不带9999端口的域名。用反向代理？你是怎么绑定你的域名blog.icehoney.me的？

**Comment by acgotaku** [comment]
@luckypoem apache 反向代理的

**Comment by bpplpp** [comment]
可以弄个简单教程吗？简介太简单了

**Comment by acgotaku** [comment]
@bpplpp 也没打算做成平台的。。。
